name: test-on-commit
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        env:
            NODE_OPTIONS: --experimental-modules
        steps:
            - uses: actions/checkout@v2
              name: Run tests using Node.js 14.x
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - run: npm install
            - run: npm test
              env:
                  CI: true
